#!/bin/bash
echo 'SYNTAX: capsort [File List] [F folder] [J Folder] [SPACEBAR Folder]'

OldIFS="$IFS"
IFS='
'
startline=$(cat "$(dirname $0)"/lineno)
lineno=0

while read -r line
do
	lineno=$((lineno+1))
	if [ $lineno -ge $startline ]
	then
		echo -n "$lineno" > "$(dirname $0)"/lineno
		choice=""
		"$(dirname $0)"/imgcat "$file"
		until [ "$choice" = "f" ] || [ "$choice" = "j" ] || [ "$choice" = " " ]
		do
			read -n 1 choice
		done
		case "$choice" in 
		"f")
			cp "$file" "$2/$RANDOM$RANDOM"-"$(basename "$file")"
			;;
		"j")
			cp "$file" "$3/$RANDOM$RANDOM"-"$(basename "$file")"
			;;
		" ")
			cp "$file" "$4/$RANDOM$RANDOM"-"$(basename "$file")"
			;;
		esac
	fi
done < $1

IFS="$OldIFS"